baseURL = "https://username.github.io/sysops-framework"
languageCode = "en-us"
title = "SysOps Framework"
# theme = "docsy"

# Content and build directories
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
staticDir = "static"
publishDir = "public"

# Enable Git info
enableGitInfo = true

# Hugo Modules
[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Site Configuration
[params]
  version_menu = "Releases"
  archived_version = false
  version = "1.0"
  url_latest_version = "https://username.github.io/sysops-framework"

  github_repo = "https://github.com/g3rhard/sysops-framework"
  github_branch = "main"

  # Enable search
  gcs_engine_id = "your-search-engine-id"

  # User interface configuration
  [params.ui]
    sidebar_menu_compact = false
    breadcrumb_disable = false
    sidebar_search_disable = false
    navbar_logo = true
    footer_about_disable = false

    # Feedback
    [params.ui.feedback]
      enable = true
      yes = 'Glad to hear it! Please <a href="https://github.com/g3rhard/sysops-framework/issues/new">tell us how we can improve</a>.'
      no = 'Sorry to hear that. Please <a href="https://github.com/g3rhard/sysops-framework/issues/new">tell us how we can improve</a>.'

    # Reading time
    [params.ui.readingtime]
      enable = false

  # Links to user social accounts (displayed in the footer)
  [params.links]
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/g3rhard/sysops-framework"
      icon = "fab fa-github"
      desc = "Development takes place here!"
    [[params.links.user]]
      name ="Twitter"
      url = "https://twitter.com/sysopsframework"
      icon = "fab fa-twitter"
      desc = "Follow us on Twitter to get the latest news!"

# Content and SEO
[params.taxonomy]
  taxonomyCloud = ["tags", "categories"]
  taxonomyCloudTitle = ["Tag Cloud", "Categories"]
  taxonomyPageHeader = ["tags", "categories"]

# Navigation
[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
  [[menu.main]]
    name = "Quick Start"
    url = "/docs/getting-started/"
    weight = 20
  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 30

# Markdown configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# Content management
[params.print]
  disable_toc = false

[params.markmap]
  enable = true

# Content structure - Fixed outputs section
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# Page bundles
[params.plantuml]
  enable = true
  theme = "default"

# Mermaid diagrams
[params.mermaid]
  enable = true
  theme = "default"
